/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./resources/ts/components/dialogs/Settings/HouseholdContainer/Add.vue')['default']
    AddHouseholdDialog: typeof import('./resources/ts/components/AddHouseholdDialog.vue')['default']
    AddHouseholdMemberDialog: typeof import('./resources/ts/components/AddHouseholdMemberDialog.vue')['default']
    AddLookupEntry: typeof import('./resources/ts/components/AddLookupEntry.vue')['default']
    AddLookupForm: typeof import('./resources/ts/components/AddLookupForm.vue')['default']
    AppBarSearch: typeof import('./resources/ts/@core/components/AppBarSearch.vue')['default']
    AppCardActions: typeof import('./resources/ts/@core/components/cards/AppCardActions.vue')['default']
    AppCardCode: typeof import('./resources/ts/@core/components/cards/AppCardCode.vue')['default']
    AppDateTimePicker: typeof import('./resources/ts/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./resources/ts/@core/components/AppDrawerHeaderSection.vue')['default']
    AppOtpInput: typeof import('./resources/ts/@core/components/app-form-elements/AppOtpInput.vue')['default']
    AppPricing: typeof import('./resources/ts/components/AppPricing.vue')['default']
    AppSearchHeader: typeof import('./resources/ts/components/AppSearchHeader.vue')['default']
    AppStepper: typeof import('./resources/ts/@core/components/AppStepper.vue')['default']
    BuyNow: typeof import('./resources/ts/@core/components/BuyNow.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/ts/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/ts/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/ts/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfirmDialog: typeof import('./resources/ts/components/dialogs/ConfirmDialog.vue')['default']
    copy: typeof import('./resources/ts/components/reports/cards/MaleMarital copy.vue')['default']
    CountGenderByA: typeof import('./resources/ts/components/reports/countGenderByA.vue')['default']
    CountGenderByAge: typeof import('./resources/ts/components/reports/countGenderByAge.vue')['default']
    CountMaleMaritalStats: typeof import('./resources/ts/components/reports/countMaleMaritalStats.vue')['default']
    CountMaritalStats: typeof import('./resources/ts/components/reports/countMaritalStats.vue')['default']
    CustomCheckboxes: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxes.vue')['default']
    CustomCheckboxesWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxesWithIcon.vue')['default']
    CustomCheckboxesWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxesWithImage.vue')['default']
    CustomizerSection: typeof import('./resources/ts/@core/components/CustomizerSection.vue')['default']
    CustomRadios: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithImage.vue')['default']
    DialogCloseBtn: typeof import('./resources/ts/@core/components/DialogCloseBtn.vue')['default']
    Edit: typeof import('./resources/ts/components/dialogs/Settings/HouseholdContainer/Edit.vue')['default']
    EditHouseholdDialog: typeof import('./resources/ts/components/EditHouseholdDialog.vue')['default']
    ErrorHeader: typeof import('./resources/ts/components/ErrorHeader.vue')['default']
    FemaleMarital: typeof import('./resources/ts/components/reports/cards/FemaleMarital.vue')['default']
    Filter: typeof import('./resources/ts/components/Filter.vue')['default']
    GenderByAge: typeof import('./resources/ts/components/reports/cards/GenderByAge.vue')['default']
    I18n: typeof import('./resources/ts/@core/components/I18n.vue')['default']
    MaleMarital: typeof import('./resources/ts/components/reports/cards/MaleMarital.vue')['default']
    MoreBtn: typeof import('./resources/ts/@core/components/MoreBtn.vue')['default']
    Notifications: typeof import('./resources/ts/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./resources/ts/@core/components/ScrollToTop.vue')['default']
    Shortcuts: typeof import('./resources/ts/@core/components/Shortcuts.vue')['default']
    SnackBar: typeof import('./resources/ts/components/SnackBar.vue')['default']
    TheCustomizer: typeof import('./resources/ts/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/ts/@core/components/ThemeSwitcher.vue')['default']
    TotalCountGender: typeof import('./resources/ts/components/reports/totalCountGender.vue')['default']
    TotalGenderCount: typeof import('./resources/ts/components/reports/cards/TotalGenderCount.vue')['default']
  }
}
