name: Laravel Vue SPA CI/CD Deployment

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ibcris/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: public_html/ibcris/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      # Laravel Backend Setup
      - name: Set up PHP for Laravel
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies for Laravel
        run: composer install --working-dir=./ --no-interaction --prefer-dist --optimize-autoloader

      # Vue Frontend Setup
      - name: Install NPM Dependencies for Vue
        run: npm install

      - name: Compile Vue Assets
        run: npm run build

      # Create directories for compressed files
      - name: Create Directories for Compressed Files
        run: |
          mkdir -p compressed_backend
          mkdir -p compressed_frontend

      # Compress Laravel Backend
      - name: Compress Laravel Backend
        run: tar -czvf compressed_backend/ibcris.tar.gz .

      # Compress Vue Frontend
      - name: Compress Vue Frontend
        run: tar -czvf compressed_frontend/ibcris-frontend.tar.gz ./public/

      # FTP Deploy Vue Frontend
      - name: Deploy Vue Frontend to Bluehost
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          server-dir: /public_html/ibcris/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./compressed_frontend/

      # FTP Deploy Laravel Backend
      - name: Deploy Laravel Backend to Bluehost
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          server-dir: /ibcris/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./compressed_backend/

      # SSH and Deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Run Post-Deployment Scripts
      - name: Run Post-Deployment Scripts
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Extract Laravel Backend
            cd /ibcris
            tar -xzvf ibcris.tar.gz
            rm ibcris.tar.gz

            # Run Laravel Migrations
            php artisan migrate --force

            # Extract Vue Frontend
            cd /public_html/ibcris
            tar -xzvf ibcris-frontend.tar.gz
            rm ibcris-frontend.tar.gz
          EOF
