name: Laravel Vue SPA CI/CD Deployment

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Cache Composer Dependencies
      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: /vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Cache NPM Dependencies
      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: /node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      # Laravel Backend Setup
      - name: Set up PHP for Laravel
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies for Laravel
        run: composer install --working-dir=./ --no-interaction --prefer-dist --optimize-autoloader

      # Vue Frontend Setup
      - name: Install NPM Dependencies for Vue
        run: npm install

      - name: Compile Vue Assets
        run: npm run build

      # SSH Key Setup
      - name: Set up SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # This is the default name, change if needed
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # Rsync Deploy Vue Frontend
      - name: Deploy Vue Frontend using Rsync
        run: |
          rsync -avzr --delete --exclude='.git*' --exclude='node_modules' --exclude='.env' \
          ./public/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:public_html/ibcris/

      # Rsync Deploy Laravel Backend
      - name: Deploy Laravel Backend using Rsync
        run: |
          rsync -avzr --delete --exclude='.git*' --exclude='vendor' --exclude='.env' \
          ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:ibcris

      # Run Post-Deployment Scripts
      - name: Run Post-Deployment Scripts
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'php artisan migrate --force'
