name: Laravel Vue SPA CI/CD Deployment

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ibcris/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: public_html/ibcris/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      # Laravel Backend Setup
      - name: Set up PHP for Laravel
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies for Laravel
        run: composer install --working-dir=./ --no-interaction --prefer-dist --optimize-autoloader

      # Vue Frontend Setup
      - name: Install NPM Dependencies for Vue
        run: npm install

      - name: Compile Vue Assets
        run: npm run build

      # SFTP Deployment for Laravel Backend
      - name: Deploy Laravel Backend to Bluehost
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/ibcris"
          rm: true # Set to true to remove the source files after transfer
          overwrite: true
          exclude: ".git*,/vendor,/storage"

      # SFTP Deployment for Vue Frontend
      - name: Deploy Vue Frontend to Bluehost
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./public/*"
          target: "/public_html/ibcris"
          rm: true # Set to true to remove the source files after transfer
          overwrite: true
          exclude: ".git*,/node_modules"

      - name: Run Post-Deployment Scripts
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /ibcris && php artisan migrate --force'
